---
title: "How I created this website"
date: 2024-01-10T08:34:30-04:00
categories:
  - experience
  - webdev
---

This is my first blog article on this website, well first blog article ever I guess. And it's about the process I followed to build it.
I downloaded the minimal mistake repo from github and began working in VSC. Since I built the Restore project website on the same computer a few months ago, I naively thought everything would work from the first try. I actually had a few errors but it was a great satisfaction to follow the recommendations I left for the Restore project members, for myself and for other readers, and every thing was quickly solved and the website was running in less than an hour.

Beginning summer 2023, I built the [Restore project website](https://www.globalrestoreproject.com/) and documented the process in a [step by step Markdown](https://www.markdownguide.org/basic-syntax/) hosted in the [Github repository.](https://github.com/global-restore-project/grp_website) In the following September, I shared with my team and interested members of iDiv a more general guide on website building, the easy way using [Github Pages.](https://pages.github.com/) This newsletter is available as a blog post [here on this website.](posts/tech-news/2023-09-22-tech-news-3/index.qmd)

Changing the domain name of the Restore website from Github Pages to a dedicated domain name was another adventure...
